#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG_FILE="/etc/keyd/default.conf"

if [ "$(id -u)" != "0" ]; then
    echo "run as root" >&2
    exit 1
fi

if [ -f "$CONFIG_FILE" ]; then
    echo "keyd config already exists, skipping..." >&2
    exit 1
fi

cat > "$CONFIG_FILE" << 'EOF'
[ids]
*

[main]
leftmeta+leftshift+f23 = rightcontrol
EOF

systemctl restart keyd.service
